var opposites_list = [
	["Causa leggera dipendenza","Causa forte dipendenza"],
	["Caldo","Freddo"],
	["Normale","Strano"],
	["Incolore","Colorato"],
	["Poche calorie","Molte Calorie"],
	["Spiacevole","Piacevole"],
	["Non essenziale","Essenziale"],
	["Economico","Costoso"],
	["Arma sottovalutata","Arma sopravvalutata"],
	["Raro","Comune"],
	["Emoji non sexy","Emoji sexy"],
	["Argomento facile da affrontare","Argomento difficile da affrontare"],
	["Sconosciuto","Famoso"],
	["Difficile da usare","Facile da usare"],
	["Stanco","Energico"],
	["Sporco","Pulito"],
	["Richiede fortuna","Richiede Abilità"],
	["Insapore","Saporito"],
	["Argomento noioso","Argomento interessante"],
	["Attore non bravo","Attore bravo"],
	["Poco originale","Hipster"],
	["Lavoro pericoloso","Lavoro sicuro"],
	["Fantasy","Fantascienza"],
	["Informale","Formale"],
	["Sottopagato","Strapagato"],
	["Asciutto","Bagnato"],
	["Abilità Sottovalutata","Abilità Sopravvalutata"],
	["Vietato","Incoraggiato"],
	["Canzone triste","Canzone allegra"],
	["Fragile","Resistente"],
	["Geek","Imbranato"],
	["Bene","Male"],
	["Il peggiore giorno dell'anno","Il migliore giorno dell'anno"],
	["Cattiva abitudine","Buona abitudine"],
	["Persona a cui piacciono i gatti","Persona a cui piacciono i cani"],
	["Amore nascosto","Amore dichiarato"],
	["Senza talento","Di talento"],
	["Scuro","Chiaro"],
	["Attore sottovalutato","Attore sopravvalutato"],
	["Difficile da trovare","Facile da trovare"],
	["Uomo brutto","Uomo bello"],
	["Difficile da ricordare","Facile da ricordare"],
	["Senza pretese intellettuali","Molto intellettuale"],
	["Malato","Sano"],
	["Uomo cattivo","Uomo buono"],
	["Storicamente importante","Storicamente irrilevante"],
	["Glabro","Peloso"],
	["Inflessibile","Flessibile"],
	["Animale domestico normale","Animale domestico esotico"],
	["Introverso","Estroverso"],
	["Meglio il libro","Meglio il film"],
	["Film brutto","Film bello"],
	["Brutto","Bello"],
	["Accade lentamente","Accade improvvisamente"],
	["Lavoro","Carriera"],
	["Amato","Odiato"],
	["Il lato chiaro della Forza","Il lato oscuro della Forza"],
	["Cattivo ingrediente per la pizza","Buon ingrediente per la pizza"],
	["Distopia","Utopia"],
	["Persona matura","Persona Immatura"],
	["Cosa sottovalutata da avere","Cosa sopravvalutata da avere"],
	["Persona malvagia","Brava persona"],
	["Film d'azione","Film d'avventura"],
	["Attività mentale","Attività fisica"],
	["Argomento controverso","Argomento non controverso"],
	["Necessità","Voglia"],
	["Cibo secco","Cibo umido"],
	["Una cosa normale da avere","Una cosa strana da avere"],
	["Dritto","Curvo"],
	["Cattiva persona","Buona persona"],
	["Anni 80","Anni 90"],
	["È etico mangiarlo","È immorale mangiarlo"],
	["Film commerciale","Film d'autore"],
	["Facoltativo","Obbligatorio"],
	["Lettera dell'alfabeto sottovalutata","Lettera dell'alfabeto sopravvalutata"],
	["Ordinario","Straordinario"],
	["Difficile da pronunciare","Facile da pronunciare"],
	["Di bassa qualità","Di alta qualità"],
	["Animale non sexy","animale sexy"],
	["Semplice","Raffinato"],
	["Dalla cattiva reputazione","Dalla buona reputazione"],
	["Fatto male","Ben fatto"],
	["Non un sandwich","Sandwich"],
	["Posto tranquillo","Posto rumoroso"],
	["Commedia","Dramma"],
	["Pericoloso","Sicuro"],
	["Culturalmente significativo","Culturalmente insignificante"],
	["Sostituibile","Insostituibile"],
	["Il peggior atleta di tutti i tempi","Il miglior atleta di tutti i tempi"],
	["Modello di comportamento","Cattiva influenza"],
	["Laurea inutile","Laurea utile"],
	["Pacifico","Bellicoso"],
	["Film sottovalutato","Film sopravvalutato"],
	["Ruvido","Liscio"],
	["Ti fa male","Ti fa bene"],
	["Rotondo","Appuntito"],
	["Prova che dio esiste","Prova che dio non esiste"],
	["Film triste","Film allegro"],
	["Perdita di tempo","Buon uso del tempo"],
	["Animale che incute paura","Animale che fa tenerezza"],
	["Di massa","Di nicchia"],
	["Dalla vita breve","Dalla vita lunga"],
	["Nessuno lo fa","Tutti lo fanno"],
	["Puzza","Profuma"],
	["Star Wars","Star Trek"],
	["Spuntino","Pasto"],
	["L'azienda meno malvagia","L'azienda più malvagia"],
	["Soffice","Duro"],
	["Cucina di sostentamento","Alta gastronomia"],
	["QUadrato","Rotondo"],
	["Meglio caldo","Meglio freddo"],
	["Stupido","Geniale"],
	["Artigianale","Industriale"],
	["Superpotere inutile","Superpotere utile"],
	["Inefficace","Efficace"],
	["Incredibile","Credibile"],
	["Volgare","Di classe"],
	["Temporaneo","Permanente"],
	["Sembra una persona","Non sembra una persona"],
	["Dal sapore cattivo","Dal sapore buono"],
	["Sport","Gioco"],
	["Non fico","Fico"],
	["La peggiore persona vivente","La migliore persona vivente"],
	["Sottovalutato","Sopravvalutato"],
	["Cibo che sporca","Cibo che non sporca"],
	["Immorale","Morale"],
	["Brutto regalo","Bel regalo"],
	["Fuori moda","Alla moda"],
	["Combattente per la libertà","Terrorista"],
	["Imperdonabile","Perdonabile"],
	["Fallimento","Capolavoro"],
	["Innocuo","Nocivo"],
	["Grifondoro","Serpeverde"],
	["Non igienico","Igienico"],
	["Musica brutta","Buona musica"],
	["Inutile","Utile"],
	["Film che verrebbe rovinato dalla presenza di Godzilla","Film che verrebbe migliorato dalla presenza di Godzilla"],
	["Non importante","Importante"],
	["Facile da compitare","Difficile da compitare"],
	["Vizio","Virtù"],
	["Musicista sottovalutato","Musicista sopravvalutato"],
	["Attività impopolare","Attività popolare"],
	["Diviso","Intero"],
	["Inaffidabile","Affidabile"],
	["Facile da uccidere","Difficile da uccidere"],
	["Instabile","Stabile"],
	["Animale rotondo","Animale appuntito"],
	["Serie tv bella","Serie tv brutta"],
	["Tradizionalmente maschile","Tradizionalmente femminile"],
	["Parte del corpo inutile","Parte del corpo utile"],
	["Moderno","Classico"],
	["Debole","Forte"],
	["Cereali disgustosi","Cereali deliziosi"],
	["Invenzione inutile","Invenzione utile"],
	["Di sinistra","Di destra"],
	["Impopolare","Popolare"],
	["Amico","Nemico"],
	["Noioso","Emozionante"],
	["Odoroso in modo cattivo","Odoroso in modo buono"],
	["Cattivo","Eroe"],
	["Cosa sottovalutata da fare","Cosa sopravvalutata da fare"],
	["Inutile durante un'emergenza","Utile durante un'emergenza"],
	["Per bambini","Per adulti"],
	["Saggio","Intelligente"],
	["Facile da fare","Difficle da fare"],
	["Inutile","Inestimabile"],
	["Natura","Cultura"],
	["Dittatura","Democrazia"],
	["Saluto normale","Saluto strano"],
	["Nome per cane","Nome per gatto"],
	["Imparziale","Fazioso"],
	["Limitato","Infinito"],
	["Evento informale","Evento formale"],
	["Cattivo investimento","Buon investimento"],
	["Conversazione leggera","Conversazione pesante"],
	["Delicato","Piccante"],
	["Religioso","Sacrilego"],
	["Non artistico","artistico"],
	["Illegale","Proibito"],
	["Popolare","Elitario"],
	["Fuori controllo","Sotto controllo"],
	["Tranquillo","Rumoroso"],
	["Pokemon non sexy","Pokemon sexy"],
	["Segreto","Noto a tutti"],
	["Troppo piccolo","Troppo grande"],
	["Breve","Lungo"],
	["Il peggior anno della storia","Il miglior anno della storia"],
	["Socialista","Capitalista"],
	["Fatto poco noto","Fatto ben noto"],
	["Fermo","Mobile"],
	["Problema locale","Problema globale"],
	["Talento","Abilità"],
	["Peggiore epoca per un viaggio nel tempo","Migliore epoca per un viaggio nell'epoca"],
	["Cosa peggiore","Cosa migliore"],
	["Numero piccolo","Numero grande"],
	["Vero","Falso"],
	["All'antica","All'avanguardia"],
	["Brutta parola","Bella parola"],
	["Piccolo","Minuscolo"],
	["Innaturale","Naturale"],
	["Persona autentica","Persona false"],
	["Derivativo","Originale"],
	["Galateo","Buone maniere"],
	["Colore non sexy","Colore sexy"],
	["A tuo beneficio","A beneficio di tutti"],
	["Impotente","Potente"],
	["Non svapa","svapa"],
	["Frutta","Verdura"],
	["Scienza","Pseudoscienza"],
	["Argomento divertente","Argomento serio"],
	["Molle","Rigido"],
	["Piacere proibito","Brutto e basta"],
	["Gossip","Notizia"],
	["È difficile sedercisi sopra","È facile sedercisi sopra"],
	["Non abbastanza","Troppo"],
	["Orizzontale","Verticale"],
	["Inodore","Odoroso"],
	["Coccoloso","Non coccoloso"],
	["Eterogeneo","Omogeneo"],
	["Inclusivo","Esclusivo"],
	["Una razza canina cattiva","Una razza canina buona"],
	["Artistico","Commerciale"],
	["Meteora","Icona del pop"],
	["Cattivo consiglio","Buon consiglio"],
	["Tic","Toc"],
	["Dolciume non buono","Dolciume buono"],
	["Tradizionale","Radicale"],
	["Cattivo sapore in bocca","Buon sapore in bocca"],
	["Illegale","Legale"],
	["Pensiero profondo","Pensiero superficiale"],
	["Scuola non buona","Buona scuola"],
	["Non è mai puntuale","È sempre puntuale"],
	["Non vivrà fino a 100 anni","Vivrà fino a 100 anni"],
	["Personaggio Disney cattivo","Persoanggio Disney buono"],
	["Simile","Identico"],
	["Cattivo presidente","Buon presidente"],
	["Bizzarro","Strano"],
	["Famoso","Famigerato"],
	["Il dio meno potente","Il dio più potente"],
	["Persona noiosa","Persona divertente"],
	["Libro sottovalutato","Libro sopravvalutato"],
	["Senso comune","Opinione estrema"],
	["La peggiore cosa da fare","La migliore cosa da fare"],
	["Specie in via d'estinzione","Specie in sovrappopolazione"],
	["Blu","Verde"],
	["Elettrizzante","Terrificante"],
	["Nerd","Palestrato"],
	["Previsto","Imprevisto"],
	["Persona che potresti picchiare","Persona che potrebbe picchiarti"],
	["Paura irrazionale","Paura razionale"],
	["Gioco sottovalutato","Gioco sopravvalutato"],
	["Cattivo","Buono"]
]
